spring.application.name=employee
app.name=employeemanagment

server.port=8051
spring.datasource.url=jdbc:postgresql://localhost:5432/gitpractice?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
